name: 'Close Stale Activity'
on:
  schedule:
    - cron: '0 10 * * 0'

jobs:
  stale:
    permissions:
        pull-requests: write
        issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
            stale-issue-message: 'This issue has been marked as stale because it has been opened 30 days without activity. Remove stale label or comment or this will be closed in 5 days.'
            stale-pr-message: 'This issue has been marked as stale because it has been opened 45 days without activity. Remove stale label or comment or this will be closed in 10 days.'
            stale-issue-label: 'stale'
            stale-pr-label: 'stale'
            close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
            close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
            days-before-issue-stale: 30
            days-before-pr-stale: 30
            days-before-issue-close: 5
            days-before-pr-close: 10
            exempt-issue-labels: never-stale,enhancement,v4.x,v5.x,good-first-issue,help-wanted,semver-major,semver-minor
            exempt-pr-labels: wip,never-stale,v4.x,v5.x,semver-major,semver-minor